### ISSUE TITLE
Feliz año ijue put aaaaaaaaa!!!

### ISSUE THREAD

**Issue by JohnGolgota** [JohnGolgota/leet#34]
Otra vez!! En contra de mi voluntad!!! Jodeeerrrrr!!!

**Comment by JohnGolgota** [comment]
Estamos frente a frente los dos
Y te confieso que has hecho con mi vida
Lo que tú has querido
Te di todo lo que pude de mí
Y aún no me quieres
Y ahora vengo a despedirme
Por que ya todo a sido imposible
Pero déjame besarte una vez más
Por que te adoro
Amor no entendiste mi vida ya lo sé
Mi amor no te interesa
Y es mejor que por fin reconozcas lo
Que soy y me aleje de ti
Amor no entendiste mi vida ya lo sé
Mi amor no te interesa
Y es mejor que por fin reconozcas lo
Que soy y me aleje de ti
Corazón si querer no puedes
Corazón por favor deshiló
Que el amor se le pasa el tiempo
Y no quiero quedarme solo en el camino
Dime ya por que me da miedo quedar
Como el ave que quedó sin nido
Ay corazón, si te vas
Enséñame como te olvido
Ay corazón, si te vas
Enséñame como te olvido
Yo tenia el presentimiento
De que tú cualquier día me olvidabas
Pero no lo hice caso al corazón
Eran ciegos mis pasos
Solo hacia realidades tus deseos
Sin pensar en mi suerte
Y ahora voy a levantarme de mis ruinas
Buscare quien me quiera
Te confieso que esto es duro para mí
Por que te adoro
Amor voy a sacar las fuerzas de mi ser
Para ver si te olvido con dolor
Aprendí de la vida que el amor no se debe rogar
Corazón si querer no puedes
Corazón por favor deshiló
Que el amor se le pasa el tiempo
Y no quiero quedarme solo en el camino
Dime ya por que me da miedo quedar
Como el ave que quedó sin nido
Ay corazón, si te vas
Enséñame como te olvido
Ay corazón, si te vas
Enséñame como te olvido

**Comment by Kolozuz** [comment]
Very nice interpretation 👏🏽

**Comment by DuvanArwenLazar** [comment]
Hopped onto PornHub, I'm 'bouta beat my dick (Nice)
Saw a fat ass so you know I had to click (Okay)
I was 'bouta nut then I realized something's wrong (What?)
I think that that's my teacher, what the fuck is goin' on?
Wait, hold it, I just had a fuckin' bruh moment

Whoa, bitch, why the fuck my teacher on some hoe shit?
Just wanted to nut, now I think I'm traumatized
I just saw my teacher getting fucked by five guys
